srcdir = '.'
blddir = '../build'
VERSION = '0.0.1'

def set_options(ctx):
    ctx.tool_options('compiler_cxx')

def configure(ctx):
    ctx.check_tool('compiler_cxx')
    ctx.check_tool('node_addon')

def build(ctx):
    t = ctx.new_task_gen('cxx', 'shlib', 'node_addon')
    t.target = 'mpBindings'
    t.source = 'msgpack.cc'
    t.includes = ['../deps/msgpack/dist/include']
    t.lib = ['msgpack']
    t.libpath = ['../deps/msgpack/dist/lib']

# vim:ts=4 sw=4 et filetype=python
